import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
    ru: {
        // Dashboard
        gastroGuide: 'GastroMap',
        overview: 'Обзор',
        map: 'Карта',
        search: 'Поиск мест...',
        aiGuide: 'AI Гид',
        logout: 'Выйти',
        world: 'Мир',
        allTypes: 'Все типы',
        allCountries: 'Все страны',
        allCities: 'Все города',
        anyPrice: 'Любая',
        language: 'Язык',
        
        // Types
        cafe: 'Кафе',
        bar: 'Бар',
        restaurant: 'Ресторан',
        market: 'Рынок',
        shop: 'Магазин',
        bakery: 'Пекарня',
        winery: 'Винодельня',
        
        // Location Card
        hiddenGem: 'Скрытое место',
        newUpdate: 'Новое',
        new: 'новых',
        cities: 'городов',
        places: 'мест',
        selectCity: 'Выберите город',
        bestPlaces: 'Лучшие места',
        nothingFound: 'Ничего не найдено',
        
        // Tabs
        discover: 'Обзор',
        saved: 'Избранное',
        done: 'Посещено',
        discoverTab: 'Обзор',
        mapTab: 'Карта',
        savedTab: 'Избранное',
        doneTab: 'Посещено',
        
        // Actions
        saved: 'В избранном',
        addToSaved: 'В избранное',
        saveToWishlist: 'В избранное',
        visited: 'Посещено',
        markVisited: 'Посетил',
        markAsVisited: 'Отметить посещённым',
        
        // Toasts & Messages
        addedToWishlist: 'Добавлено в wish-list!',
        removedFromWishlist: 'Удалено из избранного',
        markedAsVisited: 'Отмечено как посещённое!',
        removedFromVisited: 'Удалено из посещённых',
        loginToSave: 'Войдите, чтобы сохранить локацию',
        loginToAddNote: 'Войдите, чтобы добавить заметку',
        noteCannotBeEmpty: 'Заметка не может быть пустой',
        noteSaved: 'Заметка сохранена',
        noteSavedAndAdded: 'Заметка сохранена и локация добавлена в избранное!',
        linkCopied: 'Ссылка скопирована!',
        
        // Navigation
        routeInGoogleMaps: 'Маршрут в Google Maps',
        routeInAppleMaps: 'Маршрут в Apple Maps',
        
        // Additional Info
        additionalInfo: 'Дополнительная информация',
        hours: 'Часы работы',
        phone: 'Телефон',
        website: 'Веб-сайт',
        booking: 'Бронирование',
        bookNow: 'Забронировать',
        about: 'Описание',
        
        // Notes
        addPersonalNotes: 'Добавьте личные заметки об этом месте...',
        saveNoteAndAdd: 'Сохранить и добавить в избранное',
        savingNoteWillAdd: 'Сохранение заметки автоматически добавит локацию в ваш список',
        
        // Location Detail
        curatorsTip: "Curator's Tip",
        mustTry: 'Must Try',
        address: 'Адрес',
        viewOnMap: 'Посмотреть на карте',
        overview: 'Overview',
        reviews: 'Отзывы',
        myNotes: 'Мои заметки',
        personalNotes: 'Личные заметки',
        saveNote: 'Сохранить заметку',
        updated: 'Обновлено',
        helpful: 'Полезно',
        
        // Common
        back: 'Назад',
        toCountries: 'к странам',
        toCities: 'к городам',
        page: 'Стр.',
        of: 'из',
        showing: 'Показано',
        prev: 'Назад',
        next: 'Вперед',

        // Additional
        addLocation: 'Добавить локацию',
        comingSoon: 'Скоро',
        feedback: 'Обратная связь',

        // Error messages and feedback
        errorSavingLocation: 'Не удалось сохранить локацию. Попробуйте еще раз.',
        errorUpdating: 'Не удалось сохранить изменения. Попробуйте еще раз.',
        savedSuccessfully: 'Изменения сохранены',
        tryDifferentSearch: 'Попробуйте изменить поисковый запрос',
        noResultsWithFilters: 'Нет результатов с выбранными фильтрами',
        clearFilters: 'Сбросить фильтры',
        clearSearch: 'Очистить поиск',
        backToWorld: 'Вернуться к странам',
        errorSavingNote: 'Не удалось сохранить заметку. Попробуйте еще раз.',
        analyzing: 'Анализирую...',
        recommendedForYou: 'Рекомендовано для вас',
        newInYourCities: 'Новое в ваших городах',
        popularNearby: 'Популярное рядом',
        exploreByCountry: 'Исследовать по странам',
        installApp: 'Установить приложение',
        installAppDescription: 'Добавьте GastroMap на главный экран для быстрого доступа и работы офлайн',
        install: 'Установить',
        later: 'Позже',
        backOnline: 'Вы снова онлайн',
        offline: 'Офлайн режим',
        recentSearches: 'Недавние поиски',
        locations: 'Места',
        noResults: 'Ничего не найдено',
        achievements: 'Достижения',
        yourAchievements: 'Ваши достижения',
        achievementsDescription: 'Открывайте достижения, исследуя новые места',
        addedToCalendar: 'Добавлено в календарь!',
        analyzing: 'Анализирую...',

        // Feedback form
        feedbackDescription: 'Поделитесь вашими идеями, сообщите об ошибке или просто напишите нам.',
        feedbackType: 'Тип обращения',
        feedbackGeneral: 'Общий вопрос',
        feedbackBug: 'Сообщить об ошибке',
        feedbackFeature: 'Предложить идею',
        feedbackPartnership: 'Сотрудничество',
        feedbackMessage: 'Сообщение',
        feedbackPlaceholder: 'Ваше сообщение...',
        feedbackSubmit: 'Отправить',
        feedbackThanks: 'Спасибо за ваш отзыв!',
        feedbackError: 'Ошибка при отправке',

        // Profile page
        profileTitle: 'Мой профиль',
        clickToUpload: 'Нажмите на иконку, чтобы загрузить фото',
        emailCannotChange: 'Email нельзя изменить',
        profileTab: 'Профиль',
        settingsTab: 'Настройки',
        aboutYou: 'О себе',
        tellAboutYourself: 'Расскажите о себе...',
        yourName: 'Ваше имя',
        saveChanges: 'Сохранить изменения',
        profileUpdated: 'Профиль обновлен',
        avatarUploadError: 'Ошибка загрузки аватара',
        profileSaveError: 'Ошибка сохранения профиля',
        notificationsTitle: 'Уведомления',
        emailNotifications: 'Email уведомления',
        receiveNotifications: 'Получать уведомления на email',
        newLocationsNotif: 'Новые локации',
        notifyNewPlaces: 'Уведомлять о новых местах',
        locationUpdatesNotif: 'Обновления локаций',
        notifySavedChanges: 'Уведомлять об изменениях в сохраненных местах',
        marketingNotif: 'Маркетинг',
        specialOffers: 'Специальные предложения и новости',
        saveNotifSettings: 'Сохранить настройки уведомлений',
        notifSettingsSaved: 'Настройки уведомлений сохранены',
        settingsSaveError: 'Ошибка сохранения настроек',
        subscriptionsTitle: 'Подписки',
        noSubscriptions: 'Пока нет подписок',
        paidAmount: 'Оплачено',
        dataDeletion: 'Удаление данных (GDPR)',
        dataDeletionDesc: 'Согласно GDPR, вы имеете право запросить удаление всех своих персональных данных. После подтверждения запроса мы удалим все ваши данные в течение 30 дней.',
        dataWillBeDeleted: 'Будут удалены: аккаунт, сохраненные локации, заметки, отзывы и вся связанная информация.',
        requestDataDeletion: 'Запросить удаление данных',
        deletionRequestSubmitted: '✓ Запрос на удаление данных отправлен. Мы обработаем его в течение 30 дней.',
        dataExportTitle: 'Экспорт данных',
        dataExportDesc: 'Вы можете запросить копию всех ваших данных в машиночитаемом формате.',
        exportMyData: 'Экспортировать мои данные',
        dataExportComingSoon: 'Экспорт данных будет доступен в следующей версии',
        confirmDeletion: 'Вы уверены, что хотите запросить удаление всех ваших данных? Это действие необратимо.',
        deletionRequestSuccess: 'Запрос на удаление данных отправлен. Мы обработаем его в течение 30 дней.',
        requestSubmissionError: 'Ошибка отправки запроса',

        // Creator Dashboard
        creatorDashboard: 'Creator Dashboard',
        manageSubmissions: 'Управляйте своими заявками и отслеживайте производительность',
        totalLocations: 'Всего локаций',
        totalSaves: 'Всего сохранений',
        usersWhoSaved: 'Пользователей, которые сохранили ваши места',
        totalReviews: 'Всего отзывов',
        userReviewsReceived: 'Полученные отзывы пользователей',
        engagementRate: 'Уровень вовлеченности',
        avgInteractions: 'Средние взаимодействия на локацию',
        yourLocations: 'Ваши локации',
        allTab: 'Все',
        publishedTab: 'Опубликовано',
        pendingTab: 'На модерации',
        draftTab: 'Черновики',
        noLocationsInCategory: 'Пока нет локаций в этой категории',
        addFirstLocation: 'Добавить первую локацию',
        underReview: '⏳ Ваша локация на проверке у модераторов. Обычно это занимает 24-48 часов.',
        savedAsDraft: '📝 Эта локация сохранена как черновик. Отправьте на проверку, когда будете готовы.',

        // Filter Panel
        resetAll: 'Сбросить всё',
        showResults: 'Показать результаты',
        showPlaces: 'Показать',
        places: 'мест',
        activeFilter: 'активный фильтр',
        activeFilters: 'активных фильтра',

        // Special Labels
        specialtyCoffee: 'Specialty Coffee',
        coworkingSpace: 'Коворкинг',
        michelinStar: '⭐ Звезда Мишлен',
        michelinGuide: 'Рекомендация Гида Мишлен',
        fusionCuisine: 'Фьюжн Кухня',
        cozyRestaurant: 'Уютный ресторан',
        craftCocktails: 'Авторские коктейли',
        liveMusic: 'Живая музыка',
        rooftopBar: 'Крышная терраса',
        wineTasting: 'Дегустация вин',
        localFavorite: 'Любимое у местных',
        allDayBreakfast: 'Завтраки целый день',
        romanticSetting: 'Романтическая атмосфера',
        chefCuisine: 'Авторская кухня',
        extensiveWineList: 'Винная карта',
        boardGamesAvailable: 'Настольные игры',
        hookahAvailable: 'Кальян',
        streetFood: 'Стрит-фуд',
        breakfastMenu: 'Меню завтраков',
        lunchMenu: 'Меню ланча',
        lateDinner: 'Поздний ужин',
        tastyDesserts: 'Вкусные десерты',
        petFriendly: 'Pet Friendly',
        wheelchairAccessible: 'Доступно для инвалидных колясок',
        kidsPlayArea: 'Детская игровая зона',
        highChairsAvailable: 'Детские стульчики',
        outdoorSeating: 'Открытая веранда',
        parkingAvailable: 'Парковка',
        freeWifi: 'Бесплатный Wi-Fi',
        deliveryService: 'Доставка',
        takeawayAvailable: 'Самовывоз',
        quietAtmosphere: 'Тихая атмосфера',
        livelyAtmosphere: 'Оживленная атмосфера',
        scenicView: 'Живописный вид',
        happyHour: 'Счастливые часы',
        veganOptions: 'Веганские блюда',
        glutenFreeOptions: 'Безглютеновые блюда',
        locallySourcedIngredients: 'Местные продукты',
        
        // Admin Panel
        mostPopular: 'ПОПУЛЯРНО',
        filters: 'Фильтры',
        type: 'Тип',
        price: 'Цена',
        rating: 'Рейтинг',
        all: 'Все',
        any: 'Любой',
        allPrices: 'Все цены',
        anyRating: 'Любой',
        specialFeatures: 'Особенности',
        },
    uk: {
        // Dashboard
        gastroGuide: 'GastroMap',
        overview: 'Огляд',
        map: 'Карта',
        search: 'Пошук місць...',
        aiGuide: 'AI Гід',
        logout: 'Вийти',
        world: 'Світ',
        allTypes: 'Всі типи',
        allCountries: 'Всі країни',
        allCities: 'Всі міста',
        anyPrice: 'Будь-яка',
        language: 'Мова',
        
        // Types
        cafe: 'Кафе',
        bar: 'Бар',
        restaurant: 'Ресторан',
        market: 'Ринок',
        shop: 'Магазин',
        bakery: 'Пекарня',
        winery: 'Винарня',
        
        // Location Card
        hiddenGem: 'Приховане місце',
        newUpdate: 'Нове',
        new: 'нових',
        cities: 'міст',
        places: 'місць',
        selectCity: 'Оберіть місто',
        bestPlaces: 'Кращі місця',
        nothingFound: 'Нічого не знайдено',
        
        // Tabs
        discover: 'Огляд',
        saved: 'Обране',
        done: 'Відвідано',
        discoverTab: 'Огляд',
        mapTab: 'Карта',
        savedTab: 'Обране',
        doneTab: 'Відвідано',
        
        // Actions
        saved: 'В обраному',
        addToSaved: 'В обране',
        saveToWishlist: 'В обране',
        visited: 'Відвідано',
        markVisited: 'Відвідав',
        markAsVisited: 'Позначити відвіданим',
        
        // Toasts & Messages
        addedToWishlist: 'Додано в wish-list!',
        removedFromWishlist: 'Видалено з обраного',
        markedAsVisited: 'Позначено як відвідане!',
        removedFromVisited: 'Видалено з відвіданих',
        loginToSave: 'Увійдіть, щоб зберегти локацію',
        loginToAddNote: 'Увійдіть, щоб додати нотатку',
        noteCannotBeEmpty: 'Нотатка не може бути порожньою',
        noteSaved: 'Нотатку збережено',
        noteSavedAndAdded: 'Нотатку збережено та локацію додано в обране!',
        linkCopied: 'Посилання скопійовано!',
        
        // Navigation
        routeInGoogleMaps: 'Маршрут в Google Maps',
        routeInAppleMaps: 'Маршрут в Apple Maps',
        
        // Additional Info
        additionalInfo: 'Додаткова інформація',
        hours: 'Години роботи',
        phone: 'Телефон',
        website: 'Веб-сайт',
        booking: 'Бронювання',
        bookNow: 'Забронювати',
        about: 'Опис',
        
        // Notes
        addPersonalNotes: 'Додайте особисті нотатки про це місце...',
        saveNoteAndAdd: 'Зберегти і додати в обране',
        savingNoteWillAdd: 'Збереження нотатки автоматично додасть локацію у ваш список',
        
        // Location Detail
        curatorsTip: "Порада куратора",
        mustTry: 'Обов\'язково спробуйте',
        address: 'Адреса',
        viewOnMap: 'Подивитись на карті',
        overview: 'Огляд',
        reviews: 'Відгуки',
        myNotes: 'Мої нотатки',
        personalNotes: 'Особисті нотатки',
        saveNote: 'Зберегти нотатку',
        updated: 'Оновлено',
        helpful: 'Корисно',
        
        // Common
        back: 'Назад',
        toCountries: 'до країн',
        toCities: 'до міст',
        page: 'Стор.',
        of: 'з',
        showing: 'Показано',
        prev: 'Назад',
        next: 'Вперед',

        // Additional
        addLocation: 'Додати локацію',
        comingSoon: 'Незабаром',
        feedback: 'Зворотній зв\'язок',

        // Error messages and feedback
        errorSavingLocation: 'Не вдалося зберегти локацію. Спробуйте ще раз.',
        errorUpdating: 'Не вдалося зберегти зміни. Спробуйте ще раз.',
        savedSuccessfully: 'Зміни збережено',
        tryDifferentSearch: 'Спробуйте змінити пошуковий запит',
        noResultsWithFilters: 'Немає результатів з обраними фільтрами',
        clearFilters: 'Скинути фільтри',
        clearSearch: 'Очистити пошук',
        backToWorld: 'Повернутися до країн',
        errorSavingNote: 'Не вдалося зберегти нотатку. Спробуйте ще раз.',
        analyzing: 'Аналізую...',
        recommendedForYou: 'Рекомендовано для вас',
        newInYourCities: 'Нове у ваших містах',
        popularNearby: 'Популярне поруч',
        exploreByCountry: 'Досліджувати за країнами',
        installApp: 'Встановити додаток',
        installAppDescription: 'Додайте GastroMap на головний екран для швидкого доступу та роботи офлайн',
        install: 'Встановити',
        later: 'Пізніше',
        backOnline: 'Ви знову онлайн',
        offline: 'Офлайн режим',
        recentSearches: 'Останні пошуки',
        locations: 'Місця',
        noResults: 'Нічого не знайдено',
        achievements: 'Досягнення',
        yourAchievements: 'Ваші досягнення',
        achievementsDescription: 'Відкривайте досягнення, досліджуючи нові місця',
        addedToCalendar: 'Додано в календар!',
        analyzing: 'Аналізую...',

        // Feedback form
        feedbackDescription: 'Поділіться своїми ідеями, повідомте про помилку або просто напишіть нам.',
        feedbackType: 'Тип звернення',
        feedbackGeneral: 'Загальне питання',
        feedbackBug: 'Повідомити про помилку',
        feedbackFeature: 'Запропонувати ідею',
        feedbackPartnership: 'Співпраця',
        feedbackMessage: 'Повідомлення',
        feedbackPlaceholder: 'Ваше повідомлення...',
        feedbackSubmit: 'Відправити',
        feedbackThanks: 'Дякуємо за ваш відгук!',
        feedbackError: 'Помилка при відправці',

        // Profile page
        profileTitle: 'Мій профіль',
        clickToUpload: 'Натисніть на іконку, щоб завантажити фото',
        emailCannotChange: 'Email не можна змінити',
        profileTab: 'Профіль',
        settingsTab: 'Налаштування',
        aboutYou: 'Про себе',
        tellAboutYourself: 'Розкажіть про себе...',
        yourName: 'Ваше ім\'я',
        saveChanges: 'Зберегти зміни',
        profileUpdated: 'Профіль оновлено',
        avatarUploadError: 'Помилка завантаження аватара',
        profileSaveError: 'Помилка збереження профілю',
        notificationsTitle: 'Сповіщення',
        emailNotifications: 'Email сповіщення',
        receiveNotifications: 'Отримувати сповіщення на email',
        newLocationsNotif: 'Нові локації',
        notifyNewPlaces: 'Повідомляти про нові місця',
        locationUpdatesNotif: 'Оновлення локацій',
        notifySavedChanges: 'Повідомляти про зміни у збережених місцях',
        marketingNotif: 'Маркетинг',
        specialOffers: 'Спеціальні пропозиції та новини',
        saveNotifSettings: 'Зберегти налаштування сповіщень',
        notifSettingsSaved: 'Налаштування сповіщень збережено',
        settingsSaveError: 'Помилка збереження налаштувань',
        subscriptionsTitle: 'Підписки',
        noSubscriptions: 'Поки немає підписок',
        paidAmount: 'Оплачено',
        dataDeletion: 'Видалення даних (GDPR)',
        dataDeletionDesc: 'Згідно з GDPR, ви маєте право запросити видалення всіх своїх персональних даних. Після підтвердження запиту ми видалимо всі ваші дані протягом 30 днів.',
        dataWillBeDeleted: 'Будуть видалені: акаунт, збережені локації, нотатки, відгуки та вся пов\'язана інформація.',
        requestDataDeletion: 'Запросити видалення даних',
        deletionRequestSubmitted: '✓ Запит на видалення даних надіслано. Ми обробимо його протягом 30 днів.',
        dataExportTitle: 'Експорт даних',
        dataExportDesc: 'Ви можете запросити копію всіх своїх даних у машиночитаному форматі.',
        exportMyData: 'Експортувати мої дані',
        dataExportComingSoon: 'Експорт даних буде доступний у наступній версії',
        confirmDeletion: 'Ви впевнені, що хочете запросити видалення всіх своїх даних? Ця дія незворотна.',
        deletionRequestSuccess: 'Запит на видалення даних надіслано. Ми обробимо його протягом 30 днів.',
        requestSubmissionError: 'Помилка відправки запиту',

        // Creator Dashboard
        creatorDashboard: 'Creator Dashboard',
        manageSubmissions: 'Керуйте своїми заявками та відслідковуйте продуктивність',
        totalLocations: 'Всього локацій',
        totalSaves: 'Всього збережень',
        usersWhoSaved: 'Користувачів, які зберегли ваші місця',
        totalReviews: 'Всього відгуків',
        userReviewsReceived: 'Отримані відгуки користувачів',
        engagementRate: 'Рівень залученості',
        avgInteractions: 'Середні взаємодії на локацію',
        yourLocations: 'Ваші локації',
        allTab: 'Всі',
        publishedTab: 'Опубліковано',
        pendingTab: 'На модерації',
        draftTab: 'Чернетки',
        noLocationsInCategory: 'Поки немає локацій у цій категорії',
        addFirstLocation: 'Додати першу локацію',
        underReview: '⏳ Ваша локація на перевірці у модераторів. Зазвичай це займає 24-48 годин.',
        savedAsDraft: '📝 Ця локація збережена як чернетка. Відправте на перевірку, коли будете готові.',

        // Filter Panel
        resetAll: 'Скинути все',
        showResults: 'Показати результати',
        showPlaces: 'Показати',
        places: 'місць',
        activeFilter: 'активний фільтр',
        activeFilters: 'активних фільтрів',

        // Special Labels
        specialtyCoffee: 'Specialty Coffee',
        coworkingSpace: 'Коворкінг',
        michelinStar: '⭐ Зірка Мішлен',
        michelinGuide: 'Рекомендація Гіда Мішлен',
        fusionCuisine: 'Ф\'južн Кухня',
        cozyRestaurant: 'Затишний ресторан',
        craftCocktails: 'Авторські коктейлі',
        liveMusic: 'Жива музика',
        rooftopBar: 'Дахова тераса',
        wineTasting: 'Дегустація вин',
        localFavorite: 'Улюблене у місцевих',
        allDayBreakfast: 'Сніданки цілий день',
        romanticSetting: 'Романтична атмосфера',
        chefCuisine: 'Авторська кухня',
        extensiveWineList: 'Винна карта',
        boardGamesAvailable: 'Настільні ігри',
        hookahAvailable: 'Кальян',
        streetFood: 'Стріт-фуд',
        breakfastMenu: 'Меню сніданків',
        lunchMenu: 'Меню ланчу',
        lateDinner: 'Пізня вечеря',
        tastyDesserts: 'Смачні десерти',
        petFriendly: 'Pet Friendly',
        wheelchairAccessible: 'Доступно для інвалідних візків',
        kidsPlayArea: 'Дитяча ігрова зона',
        highChairsAvailable: 'Дитячі стільчики',
        outdoorSeating: 'Відкрита веранда',
        parkingAvailable: 'Парковка',
        freeWifi: 'Безкоштовний Wi-Fi',
        deliveryService: 'Доставка',
        takeawayAvailable: 'Самовивіз',
        quietAtmosphere: 'Тиха атмосфера',
        livelyAtmosphere: 'Жвава атмосфера',
        scenicView: 'Мальовничий вид',
        happyHour: 'Щасливі години',
        veganOptions: 'Веганські страви',
        glutenFreeOptions: 'Безглютенові страви',
        locallySourcedIngredients: 'Місцеві продукти',
        
        // Admin Panel
        mostPopular: 'ПОПУЛЯРНО',
        filters: 'Фільтри',
        type: 'Тип',
        price: 'Ціна',
        rating: 'Рейтинг',
        all: 'Всі',
        any: 'Будь-який',
        allPrices: 'Всі ціни',
        anyRating: 'Будь-який',
        specialFeatures: 'Особливості',
        },
    en: {
        // Dashboard
        gastroGuide: 'GastroMap',
        overview: 'Overview',
        map: 'Map',
        search: 'Search places...',
        aiGuide: 'AI Guide',
        logout: 'Logout',
        world: 'World',
        allTypes: 'All Types',
        allCountries: 'All Countries',
        allCities: 'All Cities',
        anyPrice: 'Any',
        language: 'Language',
        
        // Types
        cafe: 'Cafe',
        bar: 'Bar',
        restaurant: 'Restaurant',
        market: 'Market',
        shop: 'Shop',
        bakery: 'Bakery',
        winery: 'Winery',
        
        // Location Card
        hiddenGem: 'Hidden Gem',
        newUpdate: 'New',
        new: 'new',
        cities: 'cities',
        places: 'places',
        selectCity: 'Select City',
        bestPlaces: 'Best Places',
        nothingFound: 'Nothing found',
        
        // Tabs
        discover: 'Discover',
        saved: 'Saved',
        done: 'Visited',
        discoverTab: 'Discover',
        mapTab: 'Map',
        savedTab: 'Saved',
        doneTab: 'Visited',
        
        // Actions
        saved: 'Saved',
        addToSaved: 'Add to Saved',
        saveToWishlist: 'Save to Wishlist',
        visited: 'Visited',
        markVisited: 'Mark Visited',
        markAsVisited: 'Mark as Visited',
        
        // Toasts & Messages
        addedToWishlist: 'Added to wishlist!',
        removedFromWishlist: 'Removed from wishlist',
        markedAsVisited: 'Marked as visited!',
        removedFromVisited: 'Removed from visited',
        loginToSave: 'Login to save location',
        loginToAddNote: 'Login to add note',
        noteCannotBeEmpty: 'Note cannot be empty',
        noteSaved: 'Note saved',
        noteSavedAndAdded: 'Note saved and location added to favorites!',
        linkCopied: 'Link copied!',
        
        // Navigation
        routeInGoogleMaps: 'Route in Google Maps',
        routeInAppleMaps: 'Route in Apple Maps',
        
        // Additional Info
        additionalInfo: 'Additional Information',
        hours: 'Hours',
        phone: 'Phone',
        website: 'Website',
        booking: 'Booking',
        bookNow: 'Book Now',
        about: 'About',
        
        // Notes
        addPersonalNotes: 'Add your personal notes about this place...',
        saveNoteAndAdd: 'Save Note & Add to Saved',
        savingNoteWillAdd: 'Saving a note will automatically add this location to your list',
        
        // Location Detail
        curatorsTip: "Curator's Tip",
        mustTry: 'Must Try',
        address: 'Address',
        viewOnMap: 'View on Map',
        overview: 'Overview',
        reviews: 'Reviews',
        myNotes: 'My Notes',
        personalNotes: 'Personal Notes',
        saveNote: 'Save Note',
        updated: 'Updated',
        helpful: 'Helpful',
        
        // Common
        back: 'Back',
        toCountries: 'to countries',
        toCities: 'to cities',
        page: 'Page',
        of: 'of',
        showing: 'Showing',
        prev: 'Previous',
        next: 'Next',

        // Additional
        addLocation: 'Add Location',
        comingSoon: 'Coming Soon',
        feedback: 'Feedback',

        // Error messages and feedback
        errorSavingLocation: 'Failed to save location. Please try again.',
        errorUpdating: 'Failed to save changes. Please try again.',
        savedSuccessfully: 'Changes saved successfully',
        tryDifferentSearch: 'Try a different search query',
        noResultsWithFilters: 'No results with selected filters',
        clearFilters: 'Clear Filters',
        clearSearch: 'Clear Search',
        backToWorld: 'Back to World',
        errorSavingNote: 'Failed to save note. Please try again.',
        analyzing: 'Analyzing...',
        recommendedForYou: 'Recommended for You',
        newInYourCities: 'New in Your Cities',
        popularNearby: 'Popular Nearby',
        exploreByCountry: 'Explore by Country',
        installApp: 'Install App',
        installAppDescription: 'Add GastroMap to your home screen for quick access and offline use',
        install: 'Install',
        later: 'Later',
        backOnline: 'Back online',
        offline: 'Offline mode',
        recentSearches: 'Recent searches',
        locations: 'Locations',
        noResults: 'No results found',
        achievements: 'Achievements',
        yourAchievements: 'Your Achievements',
        achievementsDescription: 'Unlock achievements by exploring new places',
        addedToCalendar: 'Added to calendar!',
        analyzing: 'Analyzing...',

        // Feedback form
        feedbackDescription: 'Share your ideas, report a bug, or just write to us.',
        feedbackType: 'Type of request',
        feedbackGeneral: 'General question',
        feedbackBug: 'Report a bug',
        feedbackFeature: 'Suggest an idea',
        feedbackPartnership: 'Partnership',
        feedbackMessage: 'Message',
        feedbackPlaceholder: 'Your message...',
        feedbackSubmit: 'Submit',
        feedbackThanks: 'Thank you for your feedback!',
        feedbackError: 'Error sending feedback',

        // Profile page
        profileTitle: 'My Profile',
        clickToUpload: 'Click the icon to upload a photo',
        emailCannotChange: 'Email cannot be changed',
        profileTab: 'Profile',
        settingsTab: 'Settings',
        aboutYou: 'About',
        tellAboutYourself: 'Tell us about yourself...',
        yourName: 'Your name',
        saveChanges: 'Save Changes',
        profileUpdated: 'Profile updated',
        avatarUploadError: 'Avatar upload error',
        profileSaveError: 'Profile save error',
        notificationsTitle: 'Notifications',
        emailNotifications: 'Email Notifications',
        receiveNotifications: 'Receive notifications via email',
        newLocationsNotif: 'New Locations',
        notifyNewPlaces: 'Notify about new places',
        locationUpdatesNotif: 'Location Updates',
        notifySavedChanges: 'Notify about changes in saved places',
        marketingNotif: 'Marketing',
        specialOffers: 'Special offers and news',
        saveNotifSettings: 'Save Notification Settings',
        notifSettingsSaved: 'Notification settings saved',
        settingsSaveError: 'Settings save error',
        subscriptionsTitle: 'Subscriptions',
        noSubscriptions: 'No subscriptions yet',
        paidAmount: 'Paid',
        dataDeletion: 'Data Deletion (GDPR)',
        dataDeletionDesc: 'Under GDPR, you have the right to request deletion of all your personal data. After confirming the request, we will delete all your data within 30 days.',
        dataWillBeDeleted: 'Will be deleted: account, saved locations, notes, reviews and all related information.',
        requestDataDeletion: 'Request Data Deletion',
        deletionRequestSubmitted: '✓ Data deletion request submitted. We will process it within 30 days.',
        dataExportTitle: 'Data Export',
        dataExportDesc: 'You can request a copy of all your data in machine-readable format.',
        exportMyData: 'Export My Data',
        dataExportComingSoon: 'Data export will be available in the next version',
        confirmDeletion: 'Are you sure you want to request deletion of all your data? This action is irreversible.',
        deletionRequestSuccess: 'Data deletion request submitted. We will process it within 30 days.',
        requestSubmissionError: 'Request submission error',

        // Creator Dashboard
        creatorDashboard: 'Creator Dashboard',
        manageSubmissions: 'Manage your submissions and track performance',
        totalLocations: 'Total Locations',
        totalSaves: 'Total Saves',
        usersWhoSaved: 'Users who saved your places',
        totalReviews: 'Total Reviews',
        userReviewsReceived: 'User reviews received',
        engagementRate: 'Engagement Rate',
        avgInteractions: 'Avg. interactions per location',
        yourLocations: 'Your Locations',
        allTab: 'All',
        publishedTab: 'Published',
        pendingTab: 'Pending',
        draftTab: 'Draft',
        noLocationsInCategory: 'No locations in this category yet',
        addFirstLocation: 'Add Your First Location',
        underReview: '⏳ Your location is under review by our moderation team. This usually takes 24-48 hours.',
        savedAsDraft: '📝 This location is saved as a draft. Submit it for review when ready.',

        // Filter Panel
        resetAll: 'Reset All',
        showResults: 'Show Results',
        showPlaces: 'Show',
        places: 'places',
        activeFilter: 'active filter',
        activeFilters: 'active filters',

        // Special Labels
        specialtyCoffee: 'Specialty Coffee',
        coworkingSpace: 'Coworking Space',
        michelinStar: '⭐ Michelin Star',
        michelinGuide: 'Michelin Guide Recommendation',
        fusionCuisine: 'Fusion Cuisine',
        cozyRestaurant: 'Cozy Restaurant',
        craftCocktails: 'Craft Cocktails',
        liveMusic: 'Live Music',
        rooftopBar: 'Rooftop Bar',
        wineTasting: 'Wine Tasting',
        localFavorite: 'Local Favorite',
        allDayBreakfast: 'All Day Breakfast',
        romanticSetting: 'Romantic Setting',
        chefCuisine: 'Chef Cuisine',
        extensiveWineList: 'Extensive Wine List',
        boardGamesAvailable: 'Board Games',
        hookahAvailable: 'Hookah Available',
        streetFood: 'Street Food',
        breakfastMenu: 'Breakfast Menu',
        lunchMenu: 'Lunch Menu',
        lateDinner: 'Late Dinner',
        tastyDesserts: 'Tasty Desserts',
        petFriendly: 'Pet Friendly',
        wheelchairAccessible: 'Wheelchair Accessible',
        kidsPlayArea: 'Kids Play Area',
        highChairsAvailable: 'High Chairs',
        outdoorSeating: 'Outdoor Seating',
        parkingAvailable: 'Parking',
        freeWifi: 'Free Wi-Fi',
        deliveryService: 'Delivery',
        takeawayAvailable: 'Takeaway',
        quietAtmosphere: 'Quiet Atmosphere',
        livelyAtmosphere: 'Lively Atmosphere',
        scenicView: 'Scenic View',
        happyHour: 'Happy Hour',
        veganOptions: 'Vegan Options',
        glutenFreeOptions: 'Gluten-Free Options',
        locallySourcedIngredients: 'Local Ingredients',
        
        // Admin Panel
        mostPopular: 'MOST POPULAR',
        filters: 'Filters',
        type: 'Type',
        price: 'Price',
        rating: 'Rating',
        all: 'All',
        any: 'Any',
        allPrices: 'All Prices',
        anyRating: 'Any',
        specialFeatures: 'Special Features',
        },
    es: {
        // Dashboard
        gastroGuide: 'GastroMap',
        overview: 'Vista general',
        map: 'Mapa',
        search: 'Buscar lugares...',
        aiGuide: 'Guía AI',
        logout: 'Salir',
        world: 'Mundo',
        allTypes: 'Todos los tipos',
        allCountries: 'Todos los países',
        allCities: 'Todas las ciudades',
        anyPrice: 'Cualquier',
        language: 'Idioma',
        
        // Types
        cafe: 'Cafetería',
        bar: 'Bar',
        restaurant: 'Restaurante',
        market: 'Mercado',
        shop: 'Tienda',
        bakery: 'Panadería',
        winery: 'Bodega',
        
        // Location Card
        hiddenGem: 'Joya oculta',
        newUpdate: 'Nuevo',
        new: 'nuevos',
        cities: 'ciudades',
        places: 'lugares',
        selectCity: 'Seleccionar ciudad',
        bestPlaces: 'Mejores lugares',
        nothingFound: 'No se encontró nada',
        
        // Tabs
        discover: 'Descubrir',
        saved: 'Guardado',
        done: 'Visitado',
        discoverTab: 'Descubrir',
        mapTab: 'Mapa',
        savedTab: 'Guardado',
        doneTab: 'Visitado',
        
        // Actions
        saved: 'Guardado',
        addToSaved: 'Guardar',
        saveToWishlist: 'Guardar en favoritos',
        visited: 'Visitado',
        markVisited: 'Marcar visitado',
        markAsVisited: 'Marcar como visitado',
        
        // Toasts & Messages
        addedToWishlist: '¡Agregado a favoritos!',
        removedFromWishlist: 'Eliminado de favoritos',
        markedAsVisited: '¡Marcado como visitado!',
        removedFromVisited: 'Eliminado de visitados',
        loginToSave: 'Inicia sesión para guardar ubicación',
        loginToAddNote: 'Inicia sesión para agregar nota',
        noteCannotBeEmpty: 'La nota no puede estar vacía',
        noteSaved: 'Nota guardada',
        noteSavedAndAdded: '¡Nota guardada y ubicación agregada a favoritos!',
        linkCopied: '¡Enlace copiado!',
        
        // Navigation
        routeInGoogleMaps: 'Ruta en Google Maps',
        routeInAppleMaps: 'Ruta en Apple Maps',
        
        // Additional Info
        additionalInfo: 'Información adicional',
        hours: 'Horario',
        phone: 'Teléfono',
        website: 'Sitio web',
        booking: 'Reserva',
        bookNow: 'Reservar ahora',
        about: 'Acerca de',
        
        // Notes
        addPersonalNotes: 'Agrega tus notas personales sobre este lugar...',
        saveNoteAndAdd: 'Guardar nota y agregar a favoritos',
        savingNoteWillAdd: 'Guardar una nota agregará automáticamente esta ubicación a tu lista',
        
        // Location Detail
        curatorsTip: "Consejo del curador",
        mustTry: 'Debe probar',
        address: 'Dirección',
        viewOnMap: 'Ver en el mapa',
        overview: 'Resumen',
        reviews: 'Reseñas',
        myNotes: 'Mis notas',
        personalNotes: 'Notas personales',
        saveNote: 'Guardar nota',
        updated: 'Actualizado',
        helpful: 'Útil',
        
        // Common
        back: 'Atrás',
        toCountries: 'a países',
        toCities: 'a ciudades',
        page: 'Pág.',
        of: 'de',
        showing: 'Mostrando',
        prev: 'Anterior',
        next: 'Siguiente',

        // Additional
        addLocation: 'Agregar ubicación',
        comingSoon: 'Próximamente',
        feedback: 'Comentarios',

        // Error messages and feedback
        errorSavingLocation: 'Error al guardar la ubicación. Inténtelo de nuevo.',
        errorUpdating: 'Error al guardar cambios. Inténtelo de nuevo.',
        savedSuccessfully: 'Cambios guardados',
        tryDifferentSearch: 'Intente una búsqueda diferente',
        noResultsWithFilters: 'No hay resultados con los filtros seleccionados',
        clearFilters: 'Borrar Filtros',
        clearSearch: 'Borrar Búsqueda',
        backToWorld: 'Volver al Mundo',
        errorSavingNote: 'Error al guardar la nota. Inténtelo de nuevo.',
        analyzing: 'Analizando...',
        recommendedForYou: 'Recomendado para ti',
        newInYourCities: 'Nuevo en tus ciudades',
        popularNearby: 'Popular cerca',
        exploreByCountry: 'Explorar por país',
        installApp: 'Instalar aplicación',
        installAppDescription: 'Añade GastroMap a tu pantalla de inicio para acceso rápido y uso sin conexión',
        install: 'Instalar',
        later: 'Más tarde',
        backOnline: 'Conexión restaurada',
        offline: 'Modo sin conexión',
        recentSearches: 'Búsquedas recientes',
        locations: 'Lugares',
        noResults: 'No se encontraron resultados',
        achievements: 'Logros',
        yourAchievements: 'Tus logros',
        achievementsDescription: 'Desbloquea logros explorando nuevos lugares',
        addedToCalendar: '¡Añadido al calendario!',
        analyzing: 'Analizando...',

        // Feedback form
        feedbackDescription: 'Comparte tus ideas, reporta un error o simplemente escríbenos.',
        feedbackType: 'Tipo de solicitud',
        feedbackGeneral: 'Pregunta general',
        feedbackBug: 'Reportar un error',
        feedbackFeature: 'Sugerir una idea',
        feedbackPartnership: 'Colaboración',
        feedbackMessage: 'Mensaje',
        feedbackPlaceholder: 'Tu mensaje...',
        feedbackSubmit: 'Enviar',
        feedbackThanks: '¡Gracias por tu comentario!',
        feedbackError: 'Error al enviar',

        // Profile page
        profileTitle: 'Mi Perfil',
        clickToUpload: 'Haz clic en el icono para subir una foto',
        emailCannotChange: 'El email no se puede cambiar',
        profileTab: 'Perfil',
        settingsTab: 'Configuración',
        aboutYou: 'Acerca de',
        tellAboutYourself: 'Cuéntanos sobre ti...',
        yourName: 'Tu nombre',
        saveChanges: 'Guardar Cambios',
        profileUpdated: 'Perfil actualizado',
        avatarUploadError: 'Error al subir avatar',
        profileSaveError: 'Error al guardar perfil',
        notificationsTitle: 'Notificaciones',
        emailNotifications: 'Notificaciones por Email',
        receiveNotifications: 'Recibir notificaciones por email',
        newLocationsNotif: 'Nuevas Ubicaciones',
        notifyNewPlaces: 'Notificar sobre nuevos lugares',
        locationUpdatesNotif: 'Actualizaciones de Ubicaciones',
        notifySavedChanges: 'Notificar sobre cambios en lugares guardados',
        marketingNotif: 'Marketing',
        specialOffers: 'Ofertas especiales y noticias',
        saveNotifSettings: 'Guardar Configuración de Notificaciones',
        notifSettingsSaved: 'Configuración de notificaciones guardada',
        settingsSaveError: 'Error al guardar configuración',
        subscriptionsTitle: 'Suscripciones',
        noSubscriptions: 'Aún no hay suscripciones',
        paidAmount: 'Pagado',
        dataDeletion: 'Eliminación de Datos (GDPR)',
        dataDeletionDesc: 'Bajo GDPR, tienes derecho a solicitar la eliminación de todos tus datos personales. Después de confirmar la solicitud, eliminaremos todos tus datos en 30 días.',
        dataWillBeDeleted: 'Se eliminará: cuenta, ubicaciones guardadas, notas, reseñas y toda la información relacionada.',
        requestDataDeletion: 'Solicitar Eliminación de Datos',
        deletionRequestSubmitted: '✓ Solicitud de eliminación de datos enviada. La procesaremos en 30 días.',
        dataExportTitle: 'Exportar Datos',
        dataExportDesc: 'Puedes solicitar una copia de todos tus datos en formato legible por máquina.',
        exportMyData: 'Exportar Mis Datos',
        dataExportComingSoon: 'La exportación de datos estará disponible en la próxima versión',
        confirmDeletion: '¿Estás seguro de que quieres solicitar la eliminación de todos tus datos? Esta acción es irreversible.',
        deletionRequestSuccess: 'Solicitud de eliminación de datos enviada. La procesaremos en 30 días.',
        requestSubmissionError: 'Error al enviar solicitud',

        // Creator Dashboard
        creatorDashboard: 'Panel de Creador',
        manageSubmissions: 'Gestiona tus envíos y rastrea el rendimiento',
        totalLocations: 'Ubicaciones Totales',
        totalSaves: 'Guardados Totales',
        usersWhoSaved: 'Usuarios que guardaron tus lugares',
        totalReviews: 'Reseñas Totales',
        userReviewsReceived: 'Reseñas de usuarios recibidas',
        engagementRate: 'Tasa de Interacción',
        avgInteractions: 'Interacciones promedio por ubicación',
        yourLocations: 'Tus Ubicaciones',
        allTab: 'Todas',
        publishedTab: 'Publicadas',
        pendingTab: 'Pendientes',
        draftTab: 'Borradores',
        noLocationsInCategory: 'Aún no hay ubicaciones en esta categoría',
        addFirstLocation: 'Agregar Tu Primera Ubicación',
        underReview: '⏳ Tu ubicación está siendo revisada por nuestro equipo de moderación. Esto suele tardar 24-48 horas.',
        savedAsDraft: '📝 Esta ubicación está guardada como borrador. Envíala para revisión cuando estés listo.',

        // Filter Panel
        resetAll: 'Restablecer Todo',
        showResults: 'Mostrar Resultados',
        showPlaces: 'Mostrar',
        places: 'lugares',
        activeFilter: 'filtro activo',
        activeFilters: 'filtros activos',

        // Special Labels
        specialtyCoffee: 'Café de especialidad',
        coworkingSpace: 'Espacio de coworking',
        michelinStar: '⭐ Estrella Michelin',
        michelinGuide: 'Recomendación Guía Michelin',
        fusionCuisine: 'Cocina de fusión',
        cozyRestaurant: 'Restaurante acogedor',
        craftCocktails: 'Cócteles de autor',
        liveMusic: 'Música en vivo',
        rooftopBar: 'Bar en la azotea',
        wineTasting: 'Cata de vinos',
        localFavorite: 'Favorito local',
        allDayBreakfast: 'Desayuno todo el día',
        romanticSetting: 'Ambiente romántico',
        chefCuisine: 'Cocina de autor',
        extensiveWineList: 'Carta de vinos',
        boardGamesAvailable: 'Juegos de mesa',
        hookahAvailable: 'Narguile disponible',
        streetFood: 'Comida callejera',
        breakfastMenu: 'Menú de desayuno',
        lunchMenu: 'Menú de almuerzo',
        lateDinner: 'Cena tarde',
        tastyDesserts: 'Postres deliciosos',
        petFriendly: 'Acepta mascotas',
        wheelchairAccessible: 'Accesible en silla de ruedas',
        kidsPlayArea: 'Zona de juegos infantil',
        highChairsAvailable: 'Sillas altas',
        outdoorSeating: 'Terraza',
        parkingAvailable: 'Estacionamiento',
        freeWifi: 'Wi-Fi gratis',
        deliveryService: 'Entrega a domicilio',
        takeawayAvailable: 'Para llevar',
        quietAtmosphere: 'Ambiente tranquilo',
        livelyAtmosphere: 'Ambiente animado',
        scenicView: 'Vista panorámica',
        happyHour: 'Hora feliz',
        veganOptions: 'Opciones veganas',
        glutenFreeOptions: 'Sin gluten',
        locallySourcedIngredients: 'Ingredientes locales',
        
        // Admin Panel
        mostPopular: 'MÁS POPULAR',
        filters: 'Filtros',
        type: 'Tipo',
        price: 'Precio',
        rating: 'Calificación',
        all: 'Todos',
        any: 'Cualquier',
        allPrices: 'Todos los precios',
        anyRating: 'Cualquier',
        specialFeatures: 'Características especiales',
        }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        // Default to English for all users
        return 'en';
    });

    useEffect(() => {
        localStorage.setItem('appLanguage', language);
    }, [language]);

    const t = (key) => {
        // Fallback chain: current language -> English -> Russian -> key itself
        return translations[language]?.[key] || 
               translations['en']?.[key] || 
               translations['ru']?.[key] || 
               key;
    };

    const toggleLanguage = () => {
        const languages = ['ru', 'uk', 'en', 'es'];
        const currentIndex = languages.indexOf(language);
        const nextIndex = (currentIndex + 1) % languages.length;
        setLanguage(languages[nextIndex]);
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within LanguageProvider');
    }
    return context;
};